name: Email Check Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Hello from 23f2001691@ds.study.iitm.ac.in
        run: echo "Hello, this is a GitHub action step!"
